services:
  mysql:
    image: mysql:8
    container_name: pehome-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: pehome
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
